// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Asset struct {
	ID        int64
	DeviceID  int64
	PackageID int64
	SourceUrl sql.NullString
	Version   sql.NullString
}

type Device struct {
	ID                int64
	Hostname          string
	TailscaleLastSeen sql.NullInt64
	AgentLastSeen     sql.NullInt64
}

type Package struct {
	ID         int64
	Name       string
	InstallCmd string
	UpdateCmd  string
	RemoveCmd  sql.NullString
}

type Setting struct {
	ID    int64
	Name  string
	Value string
}

type TrackedService struct {
	ID             int64
	DeviceID       int64
	Name           string
	Status         string
	LastUpdated    int64
	ContainerID    sql.NullString
	ContainerImage sql.NullString
}

type WatchedService struct {
	ID   int64
	Name string
}
