// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Asset struct {
	ID        int64
	DeviceID  int64
	PackageID int64
	SourceUrl sql.NullString
	Version   sql.NullString
}

type Device struct {
	ID       int64
	Hostname string
}

type Package struct {
	ID         int64
	Name       string
	InstallCmd string
	UpdateCmd  string
	RemoveCmd  sql.NullString
}

type Setting struct {
	ID    int64
	Name  string
	Value string
}
